name: icon_to_text_extension_codespark
description: "Flutter extension to convert any IconData to inline Text or TextSpan. Material, Cupertino, and custom icon font support with rich text builder and full accessibility."
version: 1.0.0
homepage: "https://github.com/Katayath-Sai-Kiran/icon_to_text_extension_codespark"
repository: "https://github.com/Katayath-Sai-Kiran/icon_to_text_extension_codespark"
issue_tracker: "https://github.com/Katayath-Sai-Kiran/icon_to_text_extension_codespark/issues"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:
  - path: assets/screenshots/300X650-03.png
    description: Displays usage of IconData.toText with prefix and postfix styling.
    width: 300

assets:
  - assets/screenshots/
  - assets/banners/

topics:
  - icons
  - text
  - rich-text
  - material-icons
  - flutter-extensions
