name: icon_to_text_extension_codespark
description: "Flutter extension to render any IconData (Material or Cupertino) as Text or TextSpan for inline icons in rich text and custom layouts."
version: 0.0.2
homepage: "https://github.com/Katayath-Sai-Kiran/icon_to_text_extension_codespark"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:
  - path: assets/screenshots/300X650-03.png
    description: Displays usage of IconData.toText with prefix and postfix styling.
    width: 300

assets:
  - assets/screenshots/
  - assets/banners/

topics:
  - icondata
  - icons-to-text
  - material-icons
  - inline-icons
  - flutter-extensions
